function Htilde = HmatMeas(rx,ry,rz,vx,vy,vz,sx,sy,sz,svx,svy,svz,b)
%HmatMeas
%    Htilde = HmatMeas(RX,RY,RZ,VX,VY,VZ,SX,SY,SZ,SVX,SVY,SVZ,B)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    28-Apr-2024 09:02:23

t2 = rx.*2.0;
t3 = ry.*2.0;
t4 = rz.*2.0;
t5 = sx.*2.0;
t6 = sy.*2.0;
t7 = sz.*2.0;
t8 = -sx;
t10 = -sy;
t12 = -sz;
t14 = -vx;
t15 = -vy;
t16 = -vz;
t9 = -t5;
t11 = -t6;
t13 = -t7;
t17 = rx+t8;
t18 = ry+t10;
t19 = rz+t12;
t20 = svx+t14;
t21 = svy+t15;
t22 = svz+t16;
t23 = t2+t9;
t24 = t3+t11;
t25 = t17.^2;
t26 = t4+t13;
t27 = t18.^2;
t28 = t19.^2;
t29 = t17.*t20;
t30 = t18.*t21;
t31 = t19.*t22;
t32 = t25+t27+t28;
t35 = t29+t30+t31;
t33 = 1.0./sqrt(t32);
t34 = t33.^3;
Htilde = reshape([(t23.*t33)./2.0,-t20.*t33+(t23.*t34.*t35)./2.0,(t24.*t33)./2.0,-t21.*t33+(t24.*t34.*t35)./2.0,(t26.*t33)./2.0,-t22.*t33+(t26.*t34.*t35)./2.0,0.0,t17.*t33,0.0,t18.*t33,0.0,t19.*t33,0.0,0.0,1.0,0.0],[2,8]);
end
